version: '3.10'


services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    image: roz_front:latest

    ports:
      - '8080:8080'


    depends_on:
      - backend

  backend:
    image: zywczak1/backend:latest
#    build: 
#      context: ./backend
#      dockerfile: Dockerfile
#
#    environment:
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=postgres
#    volumes:
#      - ./backend:/app/backend
    ports:
      - '8000:8000'

    

    depends_on:
      - db
