# Generated by Django 5.0.3 on 2024-04-24 14:52

import django.db.models.deletion
import fundacjaROZ.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birthplace', models.CharField(max_length=100)),
                ('residential_address', models.CharField(max_length=200)),
                ('registered_address', models.CharField(max_length=200)),
                ('admission_date', models.DateField()),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('photo_path', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('residential_address', models.CharField(max_length=200)),
                ('e_mail', models.CharField(max_length=100, validators=[fundacjaROZ.models.validate_email])),
                ('legal_status', models.TextField(default='')),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('groups', models.ManyToManyField(related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundacjaROZ.children')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundacjaROZ.children')),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundacjaROZ.relatives')),
            ],
            options={
                'unique_together': {('child', 'relative')},
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(default='', max_length=100)),
                ('specification', models.CharField(default='', max_length=200)),
                ('date', models.DateField()),
                ('file_name', models.CharField(max_length=100)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundacjaROZ.children')),
                ('relative_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundacjaROZ.relatives')),
            ],
        ),
        migrations.AddField(
            model_name='children',
            name='relatives',
            field=models.ManyToManyField(through='fundacjaROZ.FamilyRelationship', to='fundacjaROZ.relatives'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundacjaROZ.children')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundacjaROZ.schools')),
            ],
        ),
        migrations.AddField(
            model_name='children',
            name='schools',
            field=models.ManyToManyField(through='fundacjaROZ.Enrollment', to='fundacjaROZ.schools'),
        ),
    ]
