# Generated by Django 4.0 on 2024-03-13 13:02

from django.db import migrations, models
import django.db.models.deletion
import fundacjaROZ.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('pesel', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, validators=[fundacjaROZ.models.validate_pesel])),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birthplace', models.CharField(max_length=100)),
                ('residential_address', models.CharField(max_length=200)),
                ('registered_address', models.CharField(max_length=200)),
                ('admission_date', models.DateField(validators=[fundacjaROZ.models.validate_admission_date])),
                ('leaving_date', models.DateField(blank=True, null=True, validators=[fundacjaROZ.models.validate_leaving_date])),
                ('photo_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Relatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('residential_address', models.CharField(max_length=200)),
                ('e_mail', models.CharField(max_length=100, validators=[fundacjaROZ.models.validate_email])),
                ('association_type', models.CharField(max_length=20)),
                ('child_pesel', models.ManyToManyField(to='fundacjaROZ.Children')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('child_pesel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundacjaROZ.children')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('doc_type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('path', models.CharField(max_length=100)),
                ('child_pesel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundacjaROZ.children')),
            ],
        ),
    ]
