# Generated by Django 5.0.3 on 2024-05-14 19:06

import fundacjaROZ.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacjaROZ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='e_mail',
            field=models.CharField(max_length=100, null=True, validators=[fundacjaROZ.models.validate_email]),
        ),
        migrations.AddField(
            model_name='schools',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
