# Generated by Django 5.0.3 on 2024-03-23 15:32 

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacjaROZ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='relatives',
            field=models.ManyToManyField(to='fundacjaROZ.relatives'),
        ),
    ]
