# Generated by Django 5.0.3 on 2024-03-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundacjaROZ', '0003_association'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='child_pesel',
            new_name='child_id',
        ),
    ]
