# Generated by Django 5.0.3 on 2024-03-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundacjaROZ', '0003_association'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Association',
        ),
    ]
