# Generated by Django 5.0.3 on 2024-03-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacjaROZ', '0004_rename_child_pesel_notes_child_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='photo_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
