# Generated by Django 5.0.3 on 2024-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacjaROZ', '0005_alter_children_photo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='photo_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
